export const plannedModels = [
  "Lead",
  "Campaign",
  "CampaignStep",
  "CampaignEnrollment",
  "SendBatch",
  "EmailAccount",
  "EmailMessage",
  "EmailEvent",
  "Suppression",
  "DiscoveryForm",
  "DiscoveryResponse",
  "Proposal",
  "Client",
  "Project",
  "TimeEntry",
  "StripeCustomer",
  "StripeInvoice",
] as const;
